name: Lint and test

on:
  push:
    branches:
      - releases/*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - run: make
      - run: make publish
