name: Lint and test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - master
      - releases/*
    paths-ignore:
      - "**.md"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - run: make deps lint
  test-build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - run: make deps test
